# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:.
version: 2.1
jobs:
  build:
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: npm install
  deploy:
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: node server.js


